### ISSUE TITLE
Cant run npx @snaplet/seed init on windows 11

### ISSUE THREAD

**Issue by Th1nhNg0** [snaplet/seed#193]
I try to run `npx @snaplet/seed init` and got this error:

```
Welcome to @snaplet/seed! Snaplet Seed populates your database with realistic, production-like mock data ✨
(node:1152) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

⠼ Installing the dependencies: `@snaplet/copycat`, `@snaplet/seed@0.98.0`Error: Command failed with exit code 1: npm install -D @snaplet/copycat @snaplet/seed@0.98.0
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @jridgewell/gen-mapping@0.3.5
npm warn Found: peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.21.0
npm warn node_modules/.pnpm/@jridgewell+gen-mapping@0.3.5/node_modules/@jridgewell/gen-mapping/node_modules/@typescript-eslint/eslint-plugin
npm warn   dev @typescript-eslint/eslint-plugin@"5.21.0" from @jridgewell/gen-mapping@0.3.5
npm warn   node_modules/.pnpm/@jridgewell+gen-mapping@0.3.5/node_modules/@jridgewell/gen-mapping
npm warn
npm warn Could not resolve dependency:
npm warn peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.21.0
npm warn node_modules/.pnpm/@jridgewell+gen-mapping@0.3.5/node_modules/@jridgewell/gen-mapping/node_modules/@typescript-eslint/eslint-plugin
npm warn   dev @typescript-eslint/eslint-plugin@"5.21.0" from @jridgewell/gen-mapping@0.3.5
npm warn   node_modules/.pnpm/@jridgewell+gen-mapping@0.3.5/node_modules/@jridgewell/gen-mapping
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @jridgewell/trace-mapping@0.3.25
npm warn Found: peer @typescript-eslint/parser@"^6.0.0 || ^6.0.0-alpha" from @typescript-eslint/eslint-plugin@6.18.1
npm warn node_modules/.pnpm/@jridgewell+trace-mapping@0.3.25/node_modules/@jridgewell/trace-mapping/node_modules/@typescript-eslint/eslint-plugin
npm warn   dev @typescript-eslint/eslint-plugin@"6.18.1" from @jridgewell/trace-mapping@0.3.25
npm warn   node_modules/.pnpm/@jridgewell+trace-mapping@0.3.25/node_modules/@jridgewell/trace-mapping
npm warn
npm warn Could not resolve dependency:
npm warn peer @typescript-eslint/parser@"^6.0.0 || ^6.0.0-alpha" from @typescript-eslint/eslint-plugin@6.18.1
npm warn node_modules/.pnpm/@jridgewell+trace-mapping@0.3.25/node_modules/@jridgewell/trace-mapping/node_modules/@typescript-eslint/eslint-plugin
npm warn   dev @typescript-eslint/eslint-plugin@"6.18.1" from @jridgewell/trace-mapping@0.3.25
npm warn   node_modules/.pnpm/@jridgewell+trace-mapping@0.3.25/node_modules/@jridgewell/trace-mapping
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: class-variance-authority@0.7.0
npm warn Found: peer @swc/core@"^1.2.66" from @swc/cli@0.1.57
npm warn node_modules/.pnpm/class-variance-authority@0.7.0/node_modules/class-variance-authority/node_modules/@swc/cli
npm warn   dev @swc/cli@"0.1.57" from class-variance-authority@0.7.0
npm warn   node_modules/.pnpm/class-variance-authority@0.7.0/node_modules/class-variance-authority
npm warn
npm warn Could not resolve dependency:
npm warn peer @swc/core@"^1.2.66" from @swc/cli@0.1.57
npm warn node_modules/.pnpm/class-variance-authority@0.7.0/node_modules/class-variance-authority/node_modules/@swc/cli
npm warn   dev @swc/cli@"0.1.57" from class-variance-authority@0.7.0
npm warn   node_modules/.pnpm/class-variance-authority@0.7.0/node_modules/class-variance-authority
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: babel-eslint@11.0.0-beta.2
npm warn Found: eslint@5.16.0
npm warn node_modules/.pnpm/cross-spawn@7.0.3/node_modules/eslint
npm warn   dev eslint@"^5.16.0" from cross-spawn@7.0.3
npm warn   node_modules/.pnpm/cross-spawn@7.0.3/node_modules/cross-spawn
npm warn     cross-spawn@7.0.3
npm warn     node_modules/.pnpm/node_modules/cross-spawn
npm warn   5 more (eslint-config-moxy, eslint-plugin-babel, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@">= 6.0.0" from babel-eslint@11.0.0-beta.2
npm warn node_modules/.pnpm/cross-spawn@7.0.3/node_modules/babel-eslint
npm warn   babel-eslint@"^11.0.0-beta.0" from eslint-config-moxy@7.1.0
npm warn   node_modules/.pnpm/cross-spawn@7.0.3/node_modules/eslint-config-moxy
npm error Cannot read properties of null (reading 'matches')
npm error A complete log of this run can be found in: C:\Users\ngoph\scoop\persist\nodejs\cache\_logs\2024-08-07T17_17_55_464Z-debug-0.log
    at makeError (file:///C:/Users/ngoph/AppData/Local/pnpm/store/v3/tmp/dlx-12956/node_modules/.pnpm/execa@8.0.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///C:/Users/ngoph/AppData/Local/pnpm/store/v3/tmp/dlx-12956/node_modules/.pnpm/execa@8.0.1/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.add (file:///C:/Users/ngoph/AppData/Local/pnpm/store/v3/tmp/dlx-12956/node_modules/.pnpm/@snaplet+seed@0.98.0_@snaplet+copycat@5.0.0/node_modules/@snaplet/seed/dist/src/config/utils.js:18:9)
    at async installDependencies (file:///C:/Users/ngoph/AppData/Local/pnpm/store/v3/tmp/dlx-12956/node_modules/.pnpm/@snaplet+seed@0.98.0_@snaplet+copycat@5.0.0/node_modules/@snaplet/seed/dist/src/cli/commands/init/installDependencies.js:29:5)
    at async initHandler (file:///C:/Users/ngoph/AppData/Local/pnpm/store/v3/tmp/dlx-12956/node_modules/.pnpm/@snaplet+seed@0.98.0_@snaplet+copycat@5.0.0/node_modules/@snaplet/seed/dist/src/cli/commands/init/initHandler.js:31:5)
    at async Object.handler (file:///C:/Users/ngoph/AppData/Local/pnpm/store/v3/tmp/dlx-12956/node_modules/.pnpm/@snaplet+seed@0.98.0_@snaplet+copycat@5.0.0/node_modules/@snaplet/seed/dist/src/cli/commands/init/init.js:8:9)
```

My node version is: v22.4.0

**Comment by angelodias-appno** [comment]
+1 here on macOS

```sh
❯ pnpx @snaplet/seed init                                                              ✘ INT at  18:09:36

Welcome to @snaplet/seed! Snaplet Seed populates your database with realistic, production-like mock data ✨
? Select an adapter to connect Seed to your database: Prisma (@prisma/client)

⠙ Installing the dependencies: `@prisma/client`, `@snaplet/copycat`, `@snaplet/seed@0.98.0`Error: Command failed with exit code 1: npm install -D @prisma/client @snaplet/copycat @snaplet/seed@0.98.0
npm error Cannot read properties of null (reading 'matches')
npm error A complete log of this run can be found in: /Users/angelodias/.npm/_logs/2025-04-21T21_09_48_284Z-debug-0.log
    at makeError (file:///Users/angelodias/.cache/pnpm/dlx/ho3lbwwldvmvsjjvlkmh6kojde/1965a2e98db-fccd/node_modules/.pnpm/execa@8.0.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///Users/angelodias/.cache/pnpm/dlx/ho3lbwwldvmvsjjvlkmh6kojde/1965a2e98db-fccd/node_modules/.pnpm/execa@8.0.1/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.add (file:///Users/angelodias/.cache/pnpm/dlx/ho3lbwwldvmvsjjvlkmh6kojde/1965a2e98db-fccd/node_modules/.pnpm/@snaplet+seed@0.98.0_@snaplet+copycat@6.0.0_openai@4.95.1_zod@3.24.3_/node_modules/@snaplet/seed/dist/src/config/utils.js:18:9)
    at async installDependencies (file:///Users/angelodias/.cache/pnpm/dlx/ho3lbwwldvmvsjjvlkmh6kojde/1965a2e98db-fccd/node_modules/.pnpm/@snaplet+seed@0.98.0_@snaplet+copycat@6.0.0_openai@4.95.1_zod@3.24.3_/node_modules/@snaplet/seed/dist/src/cli/commands/init/installDependencies.js:29:5)
    at async initHandler (file:///Users/angelodias/.cache/pnpm/dlx/ho3lbwwldvmvsjjvlkmh6kojde/1965a2e98db-fccd/node_modules/.pnpm/@snaplet+seed@0.98.0_@snaplet+copycat@6.0.0_openai@4.95.1_zod@3.24.3_/node_modules/@snaplet/seed/dist/src/cli/commands/init/initHandler.js:31:5)
    at async Object.handler (file:///Users/angelodias/.cache/pnpm/dlx/ho3lbwwldvmvsjjvlkmh6kojde/1965a2e98db-fccd/node_modules/.pnpm/@snaplet+seed@0.98.0_@snaplet+copycat@6.0.0_openai@4.95.1_zod@3.24.3_/node_modules/@snaplet/seed/dist/src/cli/commands/init/init.js:8:9)
```
